# Part 1 - Machine Learning

Task 1.1 Data preperation

In [115]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.svm import SVR
from sklearn.neural_network import MLPRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt
import random
import os

df1 = pd.read_csv('AlgerianFF_Region1.csv')
cwd = os.getcwd()
print(cwd)

print (df1)

C:\Users\PC03
     day  month  year  Temperature   RH   Ws  Rain   FFMC  DMC    DC  ISI  \
0      1      6  2012           29   57   18    0.0  65.7  3.4   7.6  1.3   
1      2      6  2012           29   61   13    1.3  64.4  4.1   7.6  1.0   
2      3      6  2012           26   82   22   13.1  47.1  2.5   7.1  0.3   
3      4      6  2012           25   89   13    2.5  28.6  1.3   6.9  0.0   
4      5      6  2012           27   77   16    0.0  64.8  3.0  14.2  1.2   
..   ...    ...   ...          ...  ...  ...    ...   ...  ...   ...  ...   
117   26      9  2012           31   54   11    0.0  82.0  6.0  16.3  2.5   
118   27      9  2012           31   66   11    0.0  85.7  8.3  24.9  4.0   
119   28      9  2012           32   47   14    0.7  77.5  7.1   8.8  1.8   
120   29      9  2012           26   80   16    1.8  47.4  2.9   7.7  0.3   
121   30      9  2012           25   78   14    1.4  45.0  1.9   7.5  0.2   

     BUI  FWI  
0    3.4  0.5  
1    3.9  0.4  
2    2.7  0.1

Splitting data for dataset into inputs & targets for Dataset 1

In [111]:
df1_inputs = df1.values[:,:-1].astype(float)
df1_targets = df1.values[:,-1].astype(float)
print(df1_inputs, df1_targets)

[[1.000e+00 6.000e+00 2.012e+03 ... 7.600e+00 1.300e+00 3.400e+00]
 [2.000e+00 6.000e+00 2.012e+03 ... 7.600e+00 1.000e+00 3.900e+00]
 [3.000e+00 6.000e+00 2.012e+03 ... 7.100e+00 3.000e-01 2.700e+00]
 ...
 [2.800e+01 9.000e+00 2.012e+03 ... 8.800e+00 1.800e+00 6.800e+00]
 [2.900e+01 9.000e+00 2.012e+03 ... 7.700e+00 3.000e-01 3.000e+00]
 [3.000e+01 9.000e+00 2.012e+03 ... 7.500e+00 2.000e-01 2.400e+00]] [ 0.5  0.4  0.1  0.   0.5  2.5  7.2  7.1  0.3  0.9  5.6  7.1  0.2  0.4
  0.1  0.   0.   0.2  1.4  0.4  2.2  2.3  3.8  7.5  8.4 10.6 15.  13.9
  3.9 12.9  0.4  0.3  0.5  1.7  4.9  6.8  3.2  8.   0.6  0.5  2.2  0.9
  3.4  0.8  0.5  0.4  3.6  6.  10.9  4.   8.8  2.8  2.1  1.3  7.3 15.3
 15.3 11.3 11.9 10.7 15.7  0.9  0.8  0.8  3.9  6.1  6.8  8.   2.6  9.9
 11.6 12.1  4.2 10.2 10.6  6.3  4.2 14.6 16.1 17.2 16.8 18.4 20.4 22.3
 20.9 20.3 13.7 13.2 19.9 30.2  4.2  0.3  0.1  0.   0.   0.5  1.7  0.9
  0.6  0.4  0.2  0.3  0.3  0.5  0.   0.1  0.   0.8  5.9  7.7  9.7  6.3
  8.3  2.8  0.7  0.7  0.

In [117]:
import pandas as pd
df2 = pd.read_csv ('AlgerianFF_Region2.csv')
data = pandas.concat([df1, df2])
print (df2)

NameError: name 'pandas' is not defined

Splitting data for dataset into inputs & targets for Dataset 2

In [ ]:
print("Second Dataset \n")
df2_inputs = df2.values[:,:-1].astype(float)
df2_targets = df2.values[:,-1].astype(float)
print(df1_inputs, df1_targets)

In [118]:
#combine df1 (dataset1) with df2 (dataset2)
output_data = df1.append(df2)
print(output_data)

     day  month  year  Temperature   RH   Ws  Rain   FFMC   DMC    DC  ISI  \
0      1      6  2012           29   57   18    0.0  65.7   3.4   7.6  1.3   
1      2      6  2012           29   61   13    1.3  64.4   4.1   7.6  1.0   
2      3      6  2012           26   82   22   13.1  47.1   2.5   7.1  0.3   
3      4      6  2012           25   89   13    2.5  28.6   1.3   6.9  0.0   
4      5      6  2012           27   77   16    0.0  64.8   3.0  14.2  1.2   
..   ...    ...   ...          ...  ...  ...    ...   ...   ...   ...  ...   
117   26      9  2012           30   65   14    0.0  85.4  16.0  44.5  4.5   
118   27      9  2012           28   87   15    4.4  41.1   6.5   8.0  0.1   
119   28      9  2012           27   87   29    0.5  45.9   3.5   7.9  0.4   
120   29      9  2012           24   54   18    0.1  79.7   4.3  15.2  1.7   
121   30      9  2012           24   64   15    0.2  67.3   3.8  16.5  1.2   

      BUI  FWI  
0     3.4  0.5  
1     3.9  0.4  
2     2.7  0

Noramlization

In [ ]:
from sklearn import preprocessing

df1_inputs = preprocessing.normalize(df1_inputs)
#print(df1_inputs)


#Scale the inputs
scaler = MinMaxScaler()
scaled = scaler.fit_transform(df1_inputs)

In [ ]:
df2_inputs = preprocessing.normalize(df2_inputs)
#print(df1_inputs)

Task 1.2 Regression 

In [ ]:
from sklearn.svm import SVR
from sklearn.neural_network import MLPRegressor
from sklearn.ensemble import RandomForestRegressor

a) Creation of regression tool for MLPRegressor

In [ ]:
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import cross_val_score



In [ ]:
regressor1 = MLPRegressor(solver='lbfgs', max_iter=4000)
regressor1.fit(df1, df1_targets)
outputs = regressor1.predict(df1)
print("Mean absolute error: ", mean_absolute_error(df1_targets, outputs))

#calculate MAE
REG1_mae = abs(cross_val_score(regressor1, df1_inputs, df1_targets, scoring="neg_mean_absolute_error"))

b) Creation of regression tool for SVR

In [ ]:
SVRregressor = SVR()
SVRregressor.fit(df1_inputs, df1_targets)
SVRoutputs = SVRregressor.predict(df1_inputs)

print("Mean absolute error: ", mean_absolute_error(df1_targets, SVRoutputs))

#calculate MAE
RFreg_mae = abs(cross_val_score(SVRregressor, df1_inputs, df1_targets, scoring="neg_mean_absolute_error")) 

c) Creation of regressor tool for RandomForestRegressor

In [ ]:
RandFor_Regressor = RandomForestRegressor()
RandFor_Regressor.fit(df1_inputs, df1_targets)
outputs =  RandFor_Regressor.predict(df1_inputs)

print("Mean absolute error: ", mean_absolute_error(df1_targets, outputs))

#calculate MAE
RandREG_mae = abs(cross_val_score(RandFor_Regressor, df1_inputs, df1_targets, scoring="neg_mean_absolute_error"))

Task 1.3 Assessment of regression

In [ ]:
# store mae results into a python array 
import matplotlib.pyplot as plt

maeArray = [REG1_mae, RFreg_mae, RandREG_mae]

REG1 = np.random.rand(100)
REG2 = np.random.randn(100)
REG3 = np.random.rand(100)

plt.figure()
plt.boxplot([REG1_mae, RFreg_mae, RandREG_mae])
plt.xticks([1,2,3], ["MLPRegressor", "SVRRegressor", "RandomForestRegressor"]);
plt.ylabel("$p(x)$")
plt.savefig("boxplot.png", bbox_inches="tight")
plt.show()

# PART 2 – EVOLUTIONARY COMPUTATION

Task 2.1 –Generation of random solutions

In [ ]:
distances = pd.read_csv(r'distances.csv', header=None)
print (distances)

In [ ]:
cities = open(r'cities.txt')
test = cities.read().splitlines()
print(test)

In [ ]:
import random
# dislaying distances

def randRoute(distances):
    route = list(range(len(distances)))
    #shuffeling cities
    random.shuffle(route)
    return route
print(randRoute(distances)) # creating a random route


#working out length of route

def route_length(route, dist):
    length = 0 #sets the varaible 'length' to zero
    for i in range(len(route)): # looks through the array
       length += dist.iat[route[i-1], route[i]] # for how many cities are in the route, get distance of first city and next city
    
    return length

x = randRoute(distances)
y = route_length(x, distances)
print(x)
print(y)
#x = randRoute(distances)
#print (x)
#y = route_length(x, distances)
#print(y)

Task 2.2 –Algorithm implementation 

2.2.1 - Creation of Ruin and Recreate function

In [ ]:
def ruinAndRecreate(iterations):
    
    RandList = []
    
    bestRoute = randRoute(distances)
    bestRouteLength = route_length(bestRoute, distances)
    
    for i in range(iterations):
        route2 = randRoute(distances)
        print(route2)
        routelength2 = route_length(route2, distances)
        if routelength2 < bestRouteLength:
            bestRouteLength = routelength2
            bestRoute = route2
        RandList.append(bestRouteLength) #iterates through and generates a new route , if it was better than previous routes it becomes the best route is kept till the next iteration 
    return RandList
#print(ruinAndRecreate(30))

2.2.1 - Creation of swap function

In [ ]:
def swap(iterations):
    print("swap Function") # for readability
    
    SwapList = []
    
    bestRoute = randRoute(distances)
    bestRouteLength = route_length(bestRoute, distances)
    
    for i in range(iterations):
        newRoute = bestRoute.copy() # copies the values of bestRoute
        newRouteLength = route_length(newRoute, distances) #records the length of the new route, and gives something to compare what route is more fitter out of the bestroute and newroute
        
        print("Best route = ", bestRoute, ": Length = ", bestRouteLength) # make sure it works
        
        newRoutePosition1 = random.randint(0, max(newRoute))
        newRoutePosition2 = random.randint(0, max(newRoute))
        
        
        newRoute[newRoutePosition1], newRoute[newRoutePosition2] = newRoute[newRoutePosition2], newRoute[newRoutePosition1]
        print("New Route = ", newRoute, ": Length = ", newRouteLength)
        newRouteLength = route_length(newRoute, distances)
        
        if(bestRouteLength > newRouteLength):
            bestRoute = newRoute
            bestRouteLength = newRouteLength
        else:
            bestRoute = bestRoute
            bestRouteLength = bestRouteLength
        SwapList.append(bestRouteLength)
        print("Best Route = ", bestRoute, ": Length = ", bestRouteLength)
        
    print("Best Route = ", route_length(bestRoute, distances))
        
    
    return SwapList

#print(swap(30))

Task 2.3 – Visualisation of results

In [ ]:
import numpy

def results():
    SwapList = []
    RuinNRecreateList = []
    
    for i in range(30):
        SwapList.append(swap(30))
        RuinNRecreateList.append(ruinAndRecreate(30))
        
        # turning both lists into numpy arrays because it works out max , min and average calculations
        Array1 = numpy.array(SwapList) 
        Array2 = numpy.array(RuinNRecreateList)

    plt.plot(Array1.min(axis=0))
    plt.plot(Array1.max(axis=0))
    plt.plot(Array1.mean(axis=0))
    
    plt.plot(Array2.min(axis=0))
    plt.plot(Array2.max(axis=0))
    plt.plot(Array2.mean(axis=0))
    plt.legend(["Swap mutation minimum","Swap mutation maximum", "Swap mutation mean", "Ruin and Recreate minimum", "Ruin and Recreate maximum", "Ruin and Recreate mean"], loc=(1,0.5))
    plt.show()
    
results()

The best mutation operator for the traveling saleman problem is the swap function because on the graph the mean value is seen traveling downwards at a faster and more reliable rate , where as the Ruin and recreate is slower. 